### ISSUE TITLE
Implementation error

### ISSUE THREAD

**Issue by PeterL1n** [Max-We/sf-zero-signal-to-noise#1]
The calculation of std is incorrect :)
```
# Change
std_pos = torch.std(x_pos)
std_cfg = torch.std(x_cfg)

# To
std_pos = torch.std(x_pos, dim=[1,2,3], keepdim=True)
std_cfg = torch.std(x_cfg, dim=[1,2,3], keepdim=True)
```

**Comment by Max-We** [comment]
Thanks for the heads-up, I saw you already mentioning this in the diffusers PR. I'm uncertain if I understand the reason behind this change, though.

Dimensions 1,2,3 are the (unet) channels, width, height (compressed) and the shape of `std_pos` is `[3, 4, 64, 64]`. By specifying `dim` we effectively calculate std for the channels, width, height separately for batch, while by omitting `dim` we calculate one std for all of these axes together in the batch. So, does this mean that this way, we preserve more detailed information (in this case on the channels, width, height axis) for the model while still rescaling the noise?

**Comment by Max-We** [comment]
I applied the changes in the most recent commit.
